/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import View=Laya.View;
import Dialog=Laya.Dialog;
import Scene=Laya.Scene;
var REG: Function = Laya.ClassUtils.regClass;
export module ui.test {
    export class BonesViewSceneUI extends Laya.Scene {
		public mCloseBtn:Laya.Button;
		public mLoop:Laya.Label;
		public mAnimLabel:Laya.Label;
		public mSleep:Laya.Label;
		public mStand:Laya.Label;
		public mWalk:Laya.Label;
		public mEat:Laya.Label;
		public mRun:Laya.Label;
		public mChangeSkin:Laya.Label;
		public mchangeHair:Laya.Label;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("test/BonesViewScene");
        }
    }
    REG("ui.test.BonesViewSceneUI",BonesViewSceneUI);
    export class ExpandPageSceneUI extends Laya.Scene {
		public mBox:Laya.Image;
		public userN:Laya.Label;
		public mClose:Laya.Button;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("test/ExpandPageScene");
        }
    }
    REG("ui.test.ExpandPageSceneUI",ExpandPageSceneUI);
    export class HumanViewUI extends Laya.Scene {
		public img:Laya.Image;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("test/HumanView");
        }
    }
    REG("ui.test.HumanViewUI",HumanViewUI);
    export class IndexPageSceneUI extends Laya.Scene {
		public mBonesBtn:Laya.Label;
		public mTestBtn:Laya.Label;
		public mRecordBtn:Laya.Label;
		public mRoundCirclePage:Laya.Label;
		public mExpandBtn:Laya.Label;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("test/IndexPageScene");
        }
    }
    REG("ui.test.IndexPageSceneUI",IndexPageSceneUI);
    export class RecordPageSceneUI extends Laya.Scene {
		public mStartBtn:Laya.Label;
		public mPauseBtn:Laya.Label;
		public mResumeBtn:Laya.Label;
		public mStopBtn:Laya.Label;
		public mInputDuration:Laya.TextInput;
		public mPlayRecord:Laya.Label;
		public mClose:Laya.Button;
		public mTab:Laya.Tab;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("test/RecordPageScene");
        }
    }
    REG("ui.test.RecordPageSceneUI",RecordPageSceneUI);
    export class RoundCircleProBarPageSceneUI extends Laya.Scene {
		public mCloseBtn:Laya.Button;
		public mCircleSprite:Laya.Sprite;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("test/RoundCircleProBarPageScene");
        }
    }
    REG("ui.test.RoundCircleProBarPageSceneUI",RoundCircleProBarPageSceneUI);
    export class TestPageSceneUI extends Laya.Scene {
		public btn:Laya.Button;
		public clip:Laya.Clip;
		public combobox:Laya.ComboBox;
		public tab:Laya.Tab;
		public list:Laya.List;
		public closeBtn:Laya.Button;
		public btn2:Laya.Button;
		public check:Laya.CheckBox;
		public radio:Laya.RadioGroup;
		public box:Laya.Box;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("test/TestPageScene");
        }
    }
    REG("ui.test.TestPageSceneUI",TestPageSceneUI);
    export class TestSceneUI extends Laya.Scene {
		public scoreLbl:Laya.Label;
		public tipLbll:Laya.Label;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("test/TestScene");
        }
    }
    REG("ui.test.TestSceneUI",TestSceneUI);
}